### ISSUE TITLE
add_coastlines call is incorrect in documentation

### ISSUE THREAD

**Issue by simonrp84** [pytroll/pycoast#46]
### Problem description

The `add_coastlines` call given on [this](https://pycoast.readthedocs.io/en/latest/high_quality_contours.html) page of the documentation is incorrect:
`cw.add_coastlines(img, (proj4_string, area_extent), resolution='l', width=0.5)`
Should be
`cw.add_coastlines(img, area_extent, resolution='l', width=0.5)`

**Comment by djhoese** [comment]
Are you sure? Do you get an error with the suggested usage? Do you have some example code that shows this issue?

**Comment by djhoese** [comment]
This should be handled here:

https://github.com/pytroll/pycoast/blob/c9584be50fa4da9f40a96b8692c1ffcf6509c797/pycoast/cw_base.py#L546-L551

**Comment by simonrp84** [comment]
I think this may have been a symptom of a problem with my conda env. I've now got a clean environment and the code on the above page works fine, still doesn't work in the old env.

I'll close this and will re-open if the problem occurs again.
