### ISSUE TITLE
Raster images without map projection

### ISSUE THREAD

**Issue by anikfal** [pytroll/pycoast#48]
Is it possible to add coastlines and borders to the images with lat/lon coordinates, which don't have any specific map projection? For example, adding borders to the composite images from MODIS L1 data.

**Comment by djhoese** [comment]
As far as I know this is not possible with pycoast or any other pytroll tool. Typically you have to resample to a projected grid(an AreaDefinition in pyresample/satpy terms) and then you can add these coastlines. Cartopy is another tool that could make a plot like you are asking for, but I believe under the hood it is essentially doing the same thing (gridding data to a set of pixels, overlaying coastlines on that grid, etc).

**Comment by anikfal** [comment]
I resampled the data to a projected grid:

**Code for resampling:**
```python
from satpy.scene import Scene
from satpy import find_files_and_readers
from datetime import datetime
from pyresample import get_area_def
files = find_files_and_readers(base_dir='/home/anikfal/datamsg8/modis',
                               reader='modis_l1b')
scn = Scene(filenames=files)
scn.load(['1'])
area_id = 'lebanon'
x_size = 1354
y_size = 2030
area_extent = (-1003877, -734860, 1003877, 880373)
proj4_string = '+proj=laea +lat_0=35 +lon_0=43 +ellps=WGS84'
description = "Lebanon"
proj_id = 'laea_lebanon'
areadef = get_area_def(area_id, description, proj_id, proj4_string, x_size, y_size, area_extent)
lcn = scn.resample(areadef, resampler='nearest')
lcn.save_datasets(writer='simple_image')
```
**Output image of the resampled data:**
![1_20200804_080000](https://user-images.githubusercontent.com/11738727/92321084-500db100-f03c-11ea-89b4-e2b50e078aea.png)

Now when I try to add the coastlines, it shows some errors.
The `proj4_string` and `area_extent` parameters have been copied from the previous code used for resampling.

**Code for adding coastlines to the resampled data:**
```python
from PIL import Image
from pycoast import ContourWriterAGG
img = Image.open('1_20200804_080000.png')  #RGB image from MSG/SEVIRI data
area_extent = (-1003877, -734860, 1003877, 880373)
proj4_string = '+proj=laea +lat_0=35 +lon_0=43 +ellps=WGS84'
area_def = (proj4_string, area_extent)
cw = ContourWriterAGG('/home/anikfal/datamsg8/gshhs_data/gshhg-shp-2.3.7')
cw.add_coastlines(img, area_def, resolution='l', level=1, outline='white', width=3)
img.show()
```
**Output errors for adding coastlines:**
>   File "7pycoast.py", line 8, in <module>
    cw.add_coastlines(img, area_def, resolution='l', level=1, outline='white', width=3)
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/pycoast/cw_agg.py", line 454, in add_coastlines
    self._add_feature(image, area_def, 'polygon', 'GSHHS',
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/pycoast/cw_base.py", line 635, in _add_feature
    return self.add_shapes(image, area_def, shape_generator, feature_type=feature_type,
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/pycoast/cw_base.py", line 553, in add_shapes
    draw = self._get_canvas(image)
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/pycoast/cw_agg.py", line 45, in _get_canvas
    return aggdraw.Draw(image)
ValueError: bad mode

**Comment by pnuu** [comment]
The `bad mode` indicates that the image is in an unsupported color mode, namely `L`. Try converting to `RGB` colorspace and see if that helps:

```python
img_rgb = img.convert('RGB')
cw.add_coastlines(img_rgb, ...)
img_rgb.show()
```

**Comment by anikfal** [comment]
@pnuu  Problem solved. Thank you.
