### ISSUE TITLE
Projections defined with extents in degrees not handled properly

### ISSUE THREAD

**Issue by pnuu** [pytroll/pycoast#7]
Projections defined with extents in degrees are not handled properly. For example EPSG:4326 (global lon/lat grid):

`from PIL import Image`
`from pycoast import ContourWriter`
`cw_ = ContourWriter()`
`img = Image.new('RGB', (2000, 1000))`
`adef = ('+init=EPSG:4326', (-180.0, -90.0, 180.0, 90.0))`
`cw_.add_coastlines(img, adef, resolution='l')`
`img.show()`

Here the extents are interpreted as metric values, thus placing the coastlines as small smudge in the center of the image.

**Comment by mraspaud** [comment]
fixed i #8
